mail_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('parcels/', views.parcels_index, name='index'),
    path('parcels/<int:parcel_id>/', views.parcels_detail, name='detail'),
    path('parcels/create/', views.ParcelCreate.as_view(), name='parcels_create'),
    path('parcels/<int:pk>/update', views.ParcelUpdate.as_view(), name='parcels_update'),
    path('parcels/<int:pk>/delete/', views.ParcelDelete.as_view(), name='parcels_delete'),
    path('parcels/<int:parcel_id>/add_pickup/', views.add_pickup, name='add_pickup'),
    path('parcels/<int:parcel_id>/add_photo/', views.add_photo, name='add_photo'),
    path('parcels/<int:parcel_id>/assoc_toy/<int:addon_id>/', views.assoc_addon, name='assoc_addon'),
    path('addons/', views.AddonsList.as_view(), name='addons_index'),
    path('addons/<int:pk>/', views.AddOnsDetail.as_view(), name='addons_detail'),
    path('addons/create/', views.AddOnsCreate.as_view(), name='addons_create'),
    path('addons/<int:pk>/update/', views.AddOnsUpdate.as_view(), name='addons_update'),
    path('addons/<int:pk>/delete/', views.AddonsDelete.as_view(), name='addons_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from datetime import date
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

TYPES = (
    ('L', 'Letter'),
    ('P', 'Package'),
    ('F', 'Flat')
)

class Addon(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('addons_detail', kwargs={'pk': self.id})

class Parcel(models.Model):
    postage = models.CharField(max_length=100)
    weight = models.IntegerField()
    destination = models.CharField(max_length=100)
    addons = models.ManyToManyField(Addon)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.postage

    def get_absolute_url(self):
        return reverse('detail', kwargs={'parcel_id': self.id})


class PickUp(models.Model):
    date = models.DateField('Pick up Date')
    type = models.CharField(max_length=1,
    choices=TYPES,
    default=TYPES[0][0]
    )

    parcel = models.ForeignKey(Parcel, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_type_display()} on {self.date}"    

    class Meta:
        ordering = ['-date']
    
class Photo(models.Model):
  url = models.CharField(max_length=200)
  parcel = models.ForeignKey(Parcel, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for cat_id: {self.parcel_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import PickUp

class PickUpForm(ModelForm):
  class Meta:
    model = PickUp
    fields = ['date', 'type']

main_app/views.py
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Parcel, Addon, Photo
from .forms import PickUpForm
import uuid
import boto3

#  class Mail:
#     def __init__(self, postage, weight, destination):
#         self.postage = postage
#         self.weight = weight
#         self.destination = destination

# parcels = [
#     Mail('International', 11, 'Mexico City'),
#     Mail('International', 11, 'Bankok'),
#     Mail('First-Class', 11, 'Dublin'),
#     Mail('First-Class', 4, 'Park City'),
#     Mail('Priority', 20, 'Charleston')
# ]

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'mail-collector-dc'

#Class Based Views
class ParcelCreate(LoginRequiredMixin, CreateView):
    model = Parcel
    fields = ['postage', 'weight', 'destination']
    success_url = '/parcels/'

    def form_valid(self, form):
        form.instance.user = self.request.user  
        return super().form_valid(form)

    

class ParcelUpdate(LoginRequiredMixin, UpdateView):
    model = Parcel
    fields = ['postage', 'weight', 'destination']

class ParcelDelete(LoginRequiredMixin, DeleteView):
    model = Parcel
    success_url = '/parcels/'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def parcels_index(request):
    parcels = Parcel.objects.filter(user=request.user)
    return render(request, 'parcels/index.html', {'parcels': parcels})

@login_required
def parcels_detail(request, parcel_id):
    parcel = Parcel.objects.get(id=parcel_id)
    addons_parcel_doesnt_have = Addon.objects.exclude(id__in = parcel.addons.all().values_list('id'))
    pickup_form = PickUpForm()
    return render(request, 'parcels/detail.html', {
        'parcel': parcel, 'pickup_form': pickup_form,
        'addons' : addons_parcel_doesnt_have
        })

@login_required
def add_pickup(request, parcel_id):
    form = PickUpForm(request.POST)
    if form.is_valid():
        new_pickup = form.save(commit=False)
        new_pickup.parcel_id = parcel_id
        new_pickup.save()
    return redirect('detail', parcel_id=parcel_id)

@login_required
def add_photo(request, parcel_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            photo = Photo(url=url, parcel_id=parcel_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', parcel_id=parcel_id)

@login_required
def assoc_addon(request, parcel_id, addon_id):
  # Note that you can pass a toy's id instead of the whole object
  Parcel.objects.get(id=parcel_id).addons.add(addon_id)
  return redirect('detail', parcel_id=parcel_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class AddonsList(LoginRequiredMixin, ListView):
  model = Addon

class AddOnsDetail(LoginRequiredMixin, DetailView):
  model = Addon

class AddOnsCreate(LoginRequiredMixin, CreateView):
  model = Addon
  fields = '__all__'

class AddOnsUpdate(LoginRequiredMixin, UpdateView):
  model = Addon
  fields = ['name', 'color']

class AddonsDelete(LoginRequiredMixin, DeleteView):
  model = Addon
  success_url = '/addons/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Mail Collector</h1>
<hr />
<p>Hire the Mail Man!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Mail Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/about" class="left brand-logo">&nbsp;&nbsp;Mail Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'addons_create' %}">Add an Add-on</a></li>
          <li><a href="{% url 'addons_index' %}">View All Add-ons</a></li>
          <li><a href="{% url 'parcels_create' %}">Create a Parcel</a></li>
          <li><a href="{% url 'index' %}">View The Manifest</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Mail Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/addon_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Addon</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'addons_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/addon_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Add-on Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ addon.name }}</span>
        <p>Color: {{ addon.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'addons_update' addon.id %}">Edit</a>
        <a href="{% url 'addons_delete' addon.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/addon_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Addon</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/addon_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Addon List</h1>

{% for addon in addon_list %}
  <a href="{% url 'addons_detail' addon.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ addon.name }}</span>
            <p>Color: {{ addon.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/parcel_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete The Parcel</h1>

  <h4>Are you sure you want to delete this <span class="teal-text">{{ object.postage }}</span> parcel ?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' parcel.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/parcel_form.html
{% extends 'base.html' %}

{% block content %}
  
  {% if object %}
    <h1>Edit the <span class="teal-text">{{object.postage}}</span> Parcel details</h1>
  {% else %}
    <h1>Add Parcel</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/parcels/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Parcel Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Postage Paid: {{ parcel.postage }}</span>
        <p>Weight: {{ parcel.weight }}</p>
        <p>Destination: {{ parcel.destination }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'parcels_update' parcel.id %}">Edit</a>
        <a href="{% url 'parcels_update' parcel.id %}">Delete</a>
      </div>
    </div>
    {% for photo in parcel.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}" alt="parcel image" />
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' parcel.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_pickup' parcel.id %}" method="post">
      {% csrf_token %}
      {{ pickup_form.as_p }}
      <input type="submit" class="btn" value="Add Pickup">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Type</th></tr>
      </thead>
      <tbody>
        {% for pickup in parcel.pickup_set.all %}
          <tr>
            <td>{{pickup.date}}</td>
            <td>{{pickup.get_type_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
	<div class="col s6">
		<h3>{{ parcel.postage }}'s Add-ons</h3>
    {% if parcel.addons.count %}
      {% for addon in parcel.addons.all %}
        <div class="card">
			<div class="card-content">
				<span class="card-title">
					A <span style="color: {{ addon.color }}">{{ addon.color }}</span> {{ addon.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Add-ons :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Add-ons</h3>
    {% if addons.count %}
      {% for addon in addons.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ addon.color }}">{{ addon.color }}</span> {{ addon.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_addon' parcel.id addon.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{parcel.postage}} Already Has All Add-ons Available</h5>
    {% endif %}
  </div>
</div>
<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  var selectEl = document.getElementById('id_type');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/parcels/index.html
{% extends 'base.html' %}
{% block content %}

<h1>The Manifest</h1>

{% for parcel in parcels %}
  <div class="card">
    <a href="{% url 'detail' parcel.id %}">
    <div class="card-content">
      <span class="card-title">{{ parcel.postage }}</span>
      <p>Postage: {{ parcel.postage }}</p>
      <p>Weight: {{ parcel.weight }} oz</p>
      <p>Delivery destination: {{parcel.destination}}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}